export const counters = [
    {
        text: "seconds have past",
        increment: 1,
        interval: 1000,
        css: "",
        icon: "timer",
    },
    {
        text: "emails have been sent",
        increment: 2398,
        interval: 10,
        css: "",
        icon: "email",
    },
    {
        text: "queries googled",
        increment: 899,
        interval: 10,
        css: "",
        icon: "search",
    },
    {
        text: "text messages sent",
        increment: 2698,
        interval: 10,
        css: "",
        icon: "message",
    },
    {
        text: "babies have been born",
        increment: 1,
        interval: 232,
        css: "",
        icon: "child_care",
    },
    {
        text: "people have died",
        increment: 1,
        interval: 555,
        css: "",
        icon: "deceased",
    },
    {
        text: "bolts of lightning have striked",
        increment: 1,
        interval: 22,
        css: "",
        icon: "bolt",
    },
    {
        text: "times your heart has beat",
        increment: 1,
        interval: 860,
        css: "",
        icon: "cardiology",
    },
    {
        text: "slices of pizza have been eaten",
        increment: 3.5,
        interval: 10,
        css: "",
        icon: "local_pizza",
    },
    {
        text: "trees have been chopped down",
        increment: 1,
        interval: 25,
        css: "",
        icon: "forest",
    },
];