export const counters = [
    {
        text: "seconds have past",
        increment: 1,
        interval: 1000,
        color: "",
        icon: "timer",
    },
    {
        text: "emails have been sent",
        increment: 2398,
        interval: 10,
        color: "#1deefd76",
        icon: "email",
    },
    {
        text: "queries googled",
        increment: 899,
        interval: 10,
        color: "#ffff2a7c",
        icon: "search",
    },
    {
        text: "text messages sent",
        increment: 2698,
        interval: 10,
        color: "#2affca7c",
        icon: "message",
    },
    {
        text: "pictures posted to Instagram",
        increment: 11,
        interval: 10,
        color: "#3ea3467c",
        icon: "image",
    },
    {
        text: "babies have been born",
        increment: 1,
        interval: 232,
        color: "#f1c38b8e",
        icon: "child_care",
    },
    {
        text: "people have died",
        increment: 1,
        interval: 555,
        color: "#5b43748e",
        icon: "deceased",
    },
    {
        text: "bolts of lightning have striked",
        increment: 1,
        interval: 22,
        color: "#5f79ff7c",
        icon: "bolt",
    },
    {
        text: "times your heart has beat",
        increment: 1,
        interval: 860,
        color: "#ff5f5f7c",
        icon: "cardiology",
    },
    {
        text: "slices of pizza have been eaten",
        increment: 3.5,
        interval: 10,
        color: "#ff9a5f7c",
        icon: "local_pizza",
    },
    {
        text: "trees have been chopped down",
        increment: 1,
        interval: 25,
        color: "#3ea3467c",
        icon: "forest",
    },
];